### ISSUE TITLE
klipper and moonraker crash loop

### ISSUE THREAD

**Issue by 4thpla** [shivajiva101/KlipperWrt#4]
Installed per video and written instructions, and mainsail interface can be accessed via IP, but only returns that it cannot connect to moonraker. Checking the logs, this part was repeated over and over:

Mon Jun 10 04:50:39 2024 daemon.err python3[3424]: Error relocating /usr/lib/libpython3.11.so.1.0: preadv2: symbol not found
Mon Jun 10 04:50:39 2024 daemon.err python3[3424]: Error relocating /usr/lib/libpython3.11.so.1.0: pwritev2: symbol not found

I think this is what's causing problems for me, could be wrong. I can upload full logs but am worried that there might be personal IP information.

**Comment by ashdavely** [comment]
i am having the same issue as well after install - but using fluidd

**Comment by shivajiva101** [comment]
Moonraker has a new dependency that wasn't satisfied by the script, all fixed! New release available v3.4
