### ISSUE TITLE
Script Errors

### ISSUE THREAD

**Issue by PeterRob** [shivajiva101/KlipperWrt#6]
Closing quotes are missing from script, e.g. install extroot :

uci set fstab.rwm="mount
uci set fstab.rwm.device="${DEVICE}
uci set fstab.rwm.target="/rwm

Fluidd repository name change from 'cadriel' to 'fluidd-core':
wget -q -O /root/fluidd/fluidd.zip https://github.com/fluidd-core/fluidd/releases/latest/download/fluidd.zip

**Comment by shivajiva101** [comment]
specifically the readme manual instructions rather than the script, well spotted :+1: 
the name change doesn't currently impact the script but may well do in future
